apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "hello-world-sample.fullname" . }}
  labels:
    app: {{ template "hello-world-sample.name" . }}
    chart: {{ template "hello-world-sample.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  custom_application.properties: |-
    server.contextPath={{ .Values.application.contextPath }}
    logging.level.org.springframework={{ .Values.application.logLevel }}